### ISSUE TITLE
Invoking `require` throws 'util is not defined'

### ISSUE THREAD

**Issue by searls** [blainesch/pry.js#20]
Using `require` just yields this:

```
pryjs> require('fs')
=>  [ReferenceError: util is not defined] ReferenceError: util is not defined
  at Object.SyncHighlight.stringify (/Users/justin/code/testdouble/waterline-parse/node_modules/pryjs/lib/pry/sync_highlight.js:26:16)
  at Object.stringify (native)
  at new SyncHighlight (/Users/justin/code/testdouble/waterline-parse/node_modules/pryjs/lib/pry/sync_highlight.js:20:29)
```

In order to get parse to work, I have to do `global.util = require('util')` at some point earlier in my script, which isn't exactly optimal.

**Comment by blainesch** [comment]
thanks! I upgraded [it here](https://github.com/blainesch/pry.js/commit/b5b0a0c4efe1a5dd24c0e52769368d6070e9276b) but it looks like `npm publish` is down right now! I'll close this ticket once `0.0.9` is up.

**Comment by blainesch** [comment]
This is part of `0.0.10` release on npm now! [:
