### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by makenova** [blainesch/pry.js#21]
I'm having trouble simply installing `pryjs` on my work machine. I'm running node `v0.12.0` and npm `2.5.1`. Here is the output that I get. Thanks.

```
➜  test  node -v
v0.12.0
➜  test  npm -v
2.5.1
➜  test  npm install --save pryjs
/
> deasync@0.0.7 install /Users/mnovaMBP/Desktop/test/node_modules/pryjs/node_modules/deasync
> node ./build.js

`darwin-x64` exists; testing
Problem with the binary; manual build incoming
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/deasync/src/deasync.o
../src/deasync.cc:5:1: error: unknown type name 'uv_idle_t'
uv_idle_t idler;
^
../src/deasync.cc:7:25: error: unknown type name 'uv_idle_t'
static void crunch_away(uv_idle_t* handle, int status) {
                        ^
../src/deasync.cc:11:32: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Run(const Arguments& args) {
                               ^~~~~~~~~
                               v8::internal::Arguments
/Users/mnovaMBP/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/deasync.cc:12:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/mnovaMBP/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/deasync.cc:14:10: error: use of undeclared identifier 'uv_default_loop'
  uv_run(uv_default_loop(), UV_RUN_ONCE);
         ^
../src/deasync.cc:15:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(Undefined());
         ~~~~~ ^
../src/deasync.cc:15:22: error: no matching function for call to 'Undefined'
  return scope.Close(Undefined());
                     ^~~~~~~~~
/Users/mnovaMBP/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were
      provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/deasync.cc:19:9: error: no member named 'SetMethod' in namespace 'node'
  node::SetMethod(target, "run", Run);
  ~~~~~~^
../src/deasync.cc:20:16: error: use of undeclared identifier 'uv_default_loop'
  uv_idle_init(uv_default_loop(), &idler);
               ^
9 errors generated.
make: *** [Release/obj.target/deasync/src/deasync.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mnovaMBP/Desktop/test/node_modules/pryjs/node_modules/deasync
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "pryjs"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.0.7 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.0.7 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mnovaMBP/Desktop/test/npm-debug.log
```

**Comment by blainesch** [comment]
Looks like it's failing on the `deasync` library. It has to compile that locally. Do you get the same error when you try to `npm install deasync` manually?

**Comment by makenova** [comment]
Nope, but it's an updated version
```
➜  test  npm install deasync
/
> deasync@0.0.10 install /Users/mnovaMBP/Desktop/test/node_modules/deasync
> node ./build.js

`darwin-x64-node-0.12` exists; testing
Binary is fine; exiting
deasync@0.0.10 node_modules/deasync
├── bindings@1.1.1
└── nan@1.6.2
```

installing `0.0.7`, the version that `pryjs` is trying to install, blows up as expected.
```
➜  test  npm install deasync@0.0.7

> deasync@0.0.7 install /Users/mnovaMBP/Desktop/test/node_modules/deasync
> node ./build.js

`darwin-x64` exists; testing
Problem with the binary; manual build incoming
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/deasync/src/deasync.o
../src/deasync.cc:5:1: error: unknown type name 'uv_idle_t'
uv_idle_t idler;
^
../src/deasync.cc:7:25: error: unknown type name 'uv_idle_t'
static void crunch_away(uv_idle_t* handle, int status) {
                        ^
../src/deasync.cc:11:32: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> Run(const Arguments& args) {
                               ^~~~~~~~~
                               v8::internal::Arguments
/Users/mnovaMBP/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/deasync.cc:12:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/mnovaMBP/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/deasync.cc:14:10: error: use of undeclared identifier 'uv_default_loop'
  uv_run(uv_default_loop(), UV_RUN_ONCE);
         ^
../src/deasync.cc:15:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(Undefined());
         ~~~~~ ^
../src/deasync.cc:15:22: error: no matching function for call to 'Undefined'
  return scope.Close(Undefined());
                     ^~~~~~~~~
/Users/mnovaMBP/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were
      provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/deasync.cc:19:9: error: no member named 'SetMethod' in namespace 'node'
  node::SetMethod(target, "run", Run);
  ~~~~~~^
../src/deasync.cc:20:16: error: use of undeclared identifier 'uv_default_loop'
  uv_idle_init(uv_default_loop(), &idler);
               ^
9 errors generated.
make: *** [Release/obj.target/deasync/src/deasync.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mnovaMBP/Desktop/test/node_modules/deasync
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "deasync@0.0.7"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! deasync@0.0.7 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.0.7 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the deasync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls deasync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mnovaMBP/Desktop/test/npm-debug.log
```

**Comment by blainesch** [comment]
Sounds like an easy fix, if you want to update the version for me I'll accept the pr. Otherwise I'll do it tonight after work. The tests will catch anything if it breaks.

**Comment by makenova** [comment]
done #22

**Comment by blainesch** [comment]
I just pushed a new version of pry `0.0.11`, can you try installing it now?

**Comment by makenova** [comment]
Works like a dream!
Thanks man. `pryjs` is awesome!
