### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'repl'

### ISSUE THREAD

**Issue by LoganDark** [blainesch/pry.js#48]
```
LoganDark:~> node
> pry = require('pryjs')
Pry {
  it: '(function () {\n      var pry, _;\n      pry = require(\'pryjs\');\n      _ = null;\n      return pry.open((function(input) {\n        return _ = eval(input);\n      }).bind(this));\n    }).call(this)' }
> eval(pry.it)
Error: ENOENT: no such file or directory, open 'repl'
  at Object.fs.openSync (fs.js:582:18)
  at Object.fs.readFileSync (fs.js:489:33)
  at File.content (/Users/LoganDark/node_modules/pryjs/build/pry/file.js:35:51)
  at File.formatted_content_by_line (/Users/LoganDark/node_modules/pryjs/build/pry/file.js:46:37)
  at Whereami.execute (/Users/LoganDark/node_modules/pryjs/build/pry/commands/whereami.js:33:34)
  at App.find_command (/Users/LoganDark/node_modules/pryjs/build/pry/app.js:65:34)
  at SyncPrompt.<anonymous> (/Users/LoganDark/node_modules/pryjs/build/pry/app.js:3:61)
  at emitTwo (events.js:106:13)
  at SyncPrompt.emit (events.js:192:7)
  at SyncPrompt.send_data (/Users/LoganDark/node_modules/pryjs/build/pry/sync_prompt.js:120:12)
  at SyncPrompt.send_data (/Users/LoganDark/node_modules/pryjs/build/pry/sync_prompt.js:3:61)
  at SyncPrompt.type (/Users/LoganDark/node_modules/pryjs/build/pry/sync_prompt.js:144:19)
  at SyncPrompt.type (/Users/LoganDark/node_modules/pryjs/build/pry/sync_prompt.js:3:61)
  at App.open (/Users/LoganDark/node_modules/pryjs/build/pry/app.js:72:19)
  at Pry.open (/Users/LoganDark/node_modules/pryjs/build/pry.js:23:18)
  at eval (<anonymous>:5:18)
  at eval (<anonymous>:8:8)
  at repl:1:1
  at ContextifyScript.Script.runInThisContext (vm.js:23:33)
  at REPLServer.defaultEval (repl.js:334:29)
  at bound (domain.js:280:14)
  at REPLServer.runBound [as eval] (domain.js:293:12)
  at REPLServer.onLine (repl.js:531:10)
  at emitOne (events.js:101:20)
  at REPLServer.emit (events.js:189:7)
  at REPLServer.Interface._onLine (readline.js:238:10)
  at REPLServer.Interface._line (readline.js:582:8)
  at REPLServer.Interface._ttyWrite (readline.js:861:14)
  at REPLServer.self._ttyWrite (repl.js:604:7)
  at ReadStream.onkeypress (readline.js:117:10)
  at emitTwo (events.js:106:13)
  at ReadStream.emit (events.js:192:7)
  at emitKeys (internal/readline.js:403:14)
  at emitKeys.next (<anonymous>:null:null)
  at ReadStream.onData (readline.js:972:36)
  at emitOne (events.js:96:13)
  at ReadStream.emit (events.js:189:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at ReadStream.Readable.push (_stream_readable.js:134:10)
  at TTY.onread (net.js:551:20)

> 
```

installed using `npm install pryjs`

**Comment by bayleedev** [comment]
Pry ships with a repl, so you don't need to run it from the node repl. If you `npm install -g pryjs` you can just run `pryjs` to start the repl.
