### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined at sync_highlight.js:45:31

### ISSUE THREAD

**Issue by mmcintyre123** [blainesch/pry.js#54]
Every time I try to use pryjs, no matter where I put it in my code, I get the following error when it encounters the statement `eval(require('pryjs').it)`:
```
TypeError: Cannot read property 'toString' of undefined
    at C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\sync_highlight.js:45:31
    at C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pygmentize-bundled\index.js:81:16
    at C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pygmentize-bundled\index.js:107:14
    at C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pygmentize-bundled\index.js:129:14
    at ChildProcess.exithandler (child_process.js:279:5)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:559:12)
    at Function.module.exports.runLoopOnce (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\deasync\index.js:66:11)
    at SyncHighlight.highlight (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\sync_highlight.js:49:19)
    at SyncHighlight.code_snippet (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\sync_highlight.js:62:20)
    at File.formatted_content_by_line (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\file.js:46:61)
    at Whereami.execute (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\commands\whereami.js:33:34)
    at App.find_command (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\app.js:65:34)
    at SyncPrompt.<anonymous> (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\app.js:3:61)
    at SyncPrompt.emit (events.js:160:13)
    at SyncPrompt.send_data (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\sync_prompt.js:120:12)
    at SyncPrompt.send_data (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\sync_prompt.js:3:61)
    at SyncPrompt.type (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\sync_prompt.js:144:19)
    at SyncPrompt.type (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\sync_prompt.js:3:61)
    at App.open (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry\app.js:72:19)
    at Pry.open (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\node_modules\pryjs\build\pry.js:23:18)
    at Timeout.eval (<anonymous>:5:18)
    at eval (<anonymous>:8:8)
    at Timeout._onTimeout (C:\Users\mmcin\GoogleDrive\CoreDocs\MyApps\getTickerPrices\sandbox\test.js:30:4)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
```

**Comment by mmcintyre123** [comment]
I added an error handler at sync_highlight.js:45:31 and discovered the real error: python was not installed.  Installed python and it fixed the issue.
